"""Per-project hermes profile management.

A profile is a HERMES_HOME directory holding the worker's accumulating state
(config, SOUL.md, memories, sessions, skills). Profiles live under the run
root (never in the repo) and are created lazily on first use. Existing files
are never overwritten: operator edits to a profile win over our template.
"""
import os
import re
from pathlib import Path

from argus.config import run_root
from argus.hermes.settings import hermes_setting

_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")

_CONFIG_TEMPLATE = """\
# Generated by Argus (hermes worker engine). Safe to edit; Argus never
# overwrites an existing file in this profile.
model:
  default: "{model}"
  provider: "{provider}"

agent:
  max_turns: {max_turns}

platform_toolsets:
  cli: "{toolsets}"

skills:
  external_dirs:
    - "{skills_dir}"
"""

_LEGACY_SOUL_TEMPLATE = """\
# SOUL

You are the dedicated Argus worker for the "{project}" project. You run
unattended on a schedule. Rules that override everything else:

- Propose only. You never push, merge, deploy, or send messages; Argus owns
  every side effect and every approval.
- Be terse and factual. Your final message is consumed by a pipeline, not a
  human chat.
- Use your memory: record project-specific lessons, recall past sessions
  before repeating work.
"""

_SOUL_TEMPLATE = """\
# SOUL

You are the dedicated Argus worker for the "{project}" project. You run
unattended on a schedule. Rules that override everything else:

- Follow the current Argus role contract exactly. In PM runs, the Developer
  edits only the isolated worktree and returns; Argus may later commit, push the
  throwaway branch, and open a PR when the project is configured for propose-pr.
- Do not merge, deploy, or send messages. Do not refuse a PM task only because a
  later Argus pipeline step is allowed to push a branch or open a PR.
- Be terse and factual. Your final message is consumed by a pipeline, not a
  human chat.
- Use your memory: record project-specific lessons, recall past sessions
  before repeating work.
"""


def home_root() -> Path:
    env = os.environ.get("ARGUS_HERMES_HOME_ROOT")
    if env:
        return Path(env)
    cfg = hermes_setting("home_root", "hermes.home_root")
    if cfg:
        return Path(cfg).expanduser()
    return run_root() / "hermes"


def ensure_profile(project: str) -> Path:
    """Resolve (and lazily create) the HERMES_HOME for a project."""
    if not project or not _NAME_RE.match(project) or all(c == "." for c in project):
        raise ValueError(f"invalid project name for hermes profile: {project!r}")
    home = home_root() / project
    home.mkdir(parents=True, exist_ok=True)

    cfg_file = home / "config.yaml"
    if not cfg_file.exists():
        cfg_file.write_text(
            _CONFIG_TEMPLATE.format(
                model=hermes_setting("model", "hermes.model") or "claude-sonnet-4-6",
                max_turns=hermes_setting("max_turns", "hermes.max_turns") or "30",
                toolsets=hermes_setting("toolset", "hermes.toolset") or "file,web,memory",
                skills_dir=(
                    hermes_setting("skills_dir", "hermes.skills_dir")
                    or str(Path("~/agent-skills").expanduser())
                ).replace('"', "").replace("\n", " "),
                provider=(
                    hermes_setting("provider", "hermes.provider") or "anthropic"
                ).replace('"', "").replace("\n", " "),
            ),
            encoding="utf-8",
        )

    soul = home / "SOUL.md"
    desired_soul = _SOUL_TEMPLATE.format(project=project)
    if not soul.exists():
        soul.write_text(desired_soul, encoding="utf-8")
    else:
        # Refresh only the old Argus-generated profile. Operator-edited SOUL
        # files still win over our template.
        legacy_soul = _LEGACY_SOUL_TEMPLATE.format(project=project)
        if soul.read_text(encoding="utf-8") == legacy_soul:
            soul.write_text(desired_soul, encoding="utf-8")

    return home
